application:
  name: DevOpsSimulator
  version: 3.0.0
  environment: hybrid
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  multi_port: [8080, 9000]
  
logging:
  level: DEBUG
  format: structured
  output: /var/log/app.log
  
features:
  auto_scaling: true
  backup_enabled: true
